### ISSUE TITLE
Constructor and method problem

### ISSUE THREAD

**Issue by terracraft321** [terracraft321/CHIP8emu#1]
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	The constructor ChipFrame(Chip) is undefined
	The method getKeyBuffer() is undefined for the type ChipFrame

	at emu.Main.<init>(Main.java:14)
	at emu.Main.main(Main.java:35)

See video:
https://www.youtube.com/watch?v=tzjPEldzS_Y&list=PL5PyurErl12czoLyYD8za68d61T_OZsP2&index=8

----
package emu;

import chip.Chip;

public class Main extends Thread {
	
	private Chip chip8;
	private ChipFrame frame;
	
	public Main() {
		chip8 = new Chip();
		chip8.init();
		chip8.loadProgram("./pong2.c8");
		frame = new ChipFrame(chip8);
	}
	
	public void run() {
		//60 hz, 60 updates per second
		while(true) {
			chip8.setKeyBuffer(frame.getKeyBuffer());
			chip8.run();
			if(chip8.needsRedraw()) {
				frame.repaint();
				chip8.removeDrawFlag();
			}
			try {
				Thread.sleep(16);
			} catch (InterruptedException e) {
				//Unthrown exception
			}
		}
	}
	
	public static void main(String[] args) {
		Main main = new Main();
		main.start();
	}

}

**Comment by terracraft321** [comment]
Issue fixed in new commit #[b62fe1f](https://github.com/terracraft321/CHIP8emu/commit/b62fe1f08340d2d2ae2066ee3862749056656c61)
